name: "TodoApp Infrastructure Pipeline"
on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  id-token: write # âœ… REQUIRED for OIDC login
  contents: read # (Optional) for accessing repo content

jobs:
  terraform_implementation:
    runs-on: self-hosted
    env:
      ARM_CLIENT_ID: 089d4a75-538e-41d9-9751-59817b989f35
      ARM_TENANT_ID: 5bb66004-782c-4c37-9c7d-578c7714c94f
      ARM_SUBSCRIPTION_ID: 0fed9206-7606-41d6-bea8-83033d2b432f
      ARM_USE_OIDC: true

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          # ClientId of the Azure Service principal created.
          client-id: 089d4a75-538e-41d9-9751-59817b989f35
          # TenantId of the Azure Service principal created.
          tenant-id: 5bb66004-782c-4c37-9c7d-578c7714c94f
          # Azure subscriptionId
          subscription-id: 0fed9206-7606-41d6-bea8-83033d2b432f

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        working-directory: environments/dev

      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: environments/dev

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: environments/dev

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        # continue-on-error: true
        working-directory: environments/dev

  terraform_apply:
    runs-on: self-hosted
    env:
      ARM_CLIENT_ID: 089d4a75-538e-41d9-9751-59817b989f35
      ARM_TENANT_ID: 5bb66004-782c-4c37-9c7d-578c7714c94f
      ARM_SUBSCRIPTION_ID: 0fed9206-7606-41d6-bea8-83033d2b432f
      ARM_USE_OIDC: true
    needs: terraform_implementation
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          # ClientId of the Azure Service principal created.
          client-id: 089d4a75-538e-41d9-9751-59817b989f35
          # TenantId of the Azure Service principal created.
          tenant-id: 5bb66004-782c-4c37-9c7d-578c7714c94f
          # Azure subscriptionId
          subscription-id: 0fed9206-7606-41d6-bea8-83033d2b432f

      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: environments/dev

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        # continue-on-error: true
        working-directory: environments/dev
